version: '3'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5432:5432
  # container_name: dev-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp:    
  